-- Generated from daggerheart.db for Consumables.

DROP TABLE IF EXISTS Consumables;

CREATE TABLE Consumables (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_name TEXT NOT NULL UNIQUE,
    subcategory TEXT,
    description_text TEXT NOT NULL,
    source_url TEXT
);

INSERT INTO Consumables (id, item_name, subcategory, description_text, source_url) VALUES
(1, 'ACIDPASTE', 'Consumable', 'This paste eats away walls and other surfaces in bright flashes.', 'https://daggerheartsrd.com/consumables/acidpaste/'),
(2, 'ARMOR STITCHER', 'Consumable', 'You can use this stitcher to spend any number of Hope and clear that many Armor Slots.', 'https://daggerheartsrd.com/consumables/armor-stitcher/'),
(3, 'ATTUNE POTION', 'Consumable', 'You gain a +1 bonus to your next Instinct Roll.', 'https://daggerheartsrd.com/consumables/attune-potion/'),
(4, 'BLINDING ORB', 'Consumable', 'You can activate this orb to create a flash of bright light. All targets within Close range become Blinded until they mark HP.', 'https://daggerheartsrd.com/consumables/blinding-orb/'),
(5, 'BLOOD OF THE YORGI', 'Consumable', 'You can drink this blood to disappear from where you are and immediately reappear at a point you can see within very Far range.', 'https://daggerheartsrd.com/consumables/blood-of-the-yorgi/'),
(6, 'BOLSTER POTION', 'Consumable', 'You gain a +1 bonus to your next Strength Roll.', 'https://daggerheartsrd.com/consumables/bolster-potion/'),
(7, 'BONDING HONEY', 'Consumable', 'This honey can be used to glue two objects together permanently.', 'https://daggerheartsrd.com/consumables/bonding-honey/'),
(8, 'BRIDGE SEED', 'Consumable', 'Thick vines grow from your location to a point of your choice within Far range, allowing you to climb up or across them. The vines dissipate on your next short rest.', 'https://daggerheartsrd.com/consumables/bridge-seed/'),
(9, 'CHANNELSTONE', 'Consumable', 'You can use this stone to take a spell or grimoire from your vault, use it once, and return it to your vault.', 'https://daggerheartsrd.com/consumables/channelstone/'),
(10, 'CHARM POTION', 'Consumable', 'You gain a +1 bonus to your next Presence Roll.', 'https://daggerheartsrd.com/consumables/charm-potion/'),
(11, 'CIRCLE OF THE VOID', 'Consumable', 'Mark a Stress to create a void that extends up to Far range. No magic can be cast inside the void, and creatures within the void are immune to magic damage.', 'https://daggerheartsrd.com/consumables/circle-of-the-void/'),
(12, 'CONTROL POTION', 'Consumable', 'You gain a +1 bonus to your next Finesse Roll.', 'https://daggerheartsrd.com/consumables/control-potion/'),
(13, 'DEATH TEA', 'Consumable', 'After you drink this tea, you instantly kill your target when you critically succeed on an attack. If you don''t critically succeed on an attack before your next long rest, you die.', 'https://daggerheartsrd.com/consumables/death-tea/'),
(14, 'DRAGONBLOOM TEA', 'Consumable', 'You can drink this tea to unleash a fiery breath attack. Make an Instinct Roll against all adversaries in front of you within Close range. Targets you succeed against take 2d20 physical damage using your Proficiency.', 'https://daggerheartsrd.com/consumables/dragonbloom-tea/'),
(15, 'DRIPFANG POISON', 'Consumable', 'A creature who consumes this poison takes 8d10 direct magic damage.', 'https://daggerheartsrd.com/consumables/dripfang-poison/'),
(16, 'ENLIGHTEN POTION', 'Consumable', 'You gain a +1 bonus to your next Knowledge Roll.', 'https://daggerheartsrd.com/consumables/enlighten-potion/'),
(17, 'FEAST OF XURLA', 'Consumable', 'You can eat this meal to clear all HP and Stress and gain 1d4 Hope.', 'https://daggerheartsrd.com/consumables/feast-of-xurla/'),
(18, 'FEATHERBONE', 'Consumable', 'You can use this bone to control your falling speed for a number of minutes equal to your level.', 'https://daggerheartsrd.com/consumables/featherbone/'),
(19, 'GILL SALVE', 'Consumable', 'You can apply this salve to your neck to breathe underwater for a number of minutes equal to your level.', 'https://daggerheartsrd.com/consumables/gill-salve/'),
(20, 'GROWING POTION', 'Consumable', 'You can drink this potion to double your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Strength and a +1 bonus to your Proficiency.', 'https://daggerheartsrd.com/consumables/growing-potion/'),
(21, 'Grindletooth VENOM', 'Consumable', 'You can apply this venom to a weapon that deals physical damage to add a d6 to your next damage roll with that weapon.', 'https://daggerheartsrd.com/consumables/grindletooth-venom/'),
(22, 'HEALTH POTION', 'Consumable', 'Clear 1d4+1 HP.', 'https://daggerheartsrd.com/consumables/health-potion/'),
(23, 'HOMET''S SECRET POTION', 'Consumable', 'After drinking this potion, the next successful attack you make critically succeeds.', 'https://daggerheartsrd.com/consumables/hornets-secret-potion/'),
(24, 'HOPEHOLD FLARE', 'Consumable', 'When you use this flare, allies within Close range roll a d6 when they spend a Hope. On a result of 6, they gain the effect of that Hope without spending it. The flare lasts until the end of the scene.', 'https://daggerheartsrd.com/consumables/hopehold-flare/'),
(25, 'IMPROVED ARCANE SHARD', 'Consumable', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 2d20 magic damage.', 'https://daggerheartsrd.com/consumables/improved-arcane-shard/'),
(26, 'IMPROVED Grindletooth VENOM', 'Consumable', 'You can apply this venom to a weapon that deals physical damage to add a d8 to your next damage roll with that weapon.', 'https://daggerheartsrd.com/consumables/improved-grindletooth-venom/'),
(27, 'JAR OF LOST VOICES', 'Consumable', 'You can open this jar to release a deafening echo of voices for a number of minutes equal to your Instinct. Creatures within Far range unprepared for the sound take 6d8 magic damage.', 'https://daggerheartsrd.com/consumables/jar-of-lost-voices/'),
(28, 'JUMPING ROOT', 'Consumable', 'Eat this root to leap up to Far range once without needing to roll.', 'https://daggerheartsrd.com/consumables/jumping-root/'),
(29, 'KNOWLEDGE STONE', 'Consumable', 'If you die while holding this stone, an ally can take a card from your loadout to place in their loadout or vault. After they take this knowledge, the stone crumbles.', 'https://daggerheartsrd.com/consumables/knowledge-stone/'),
(30, 'MAJOR ARCANE SHARD', 'Consumable', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 4d20 magic damage.', 'https://daggerheartsrd.com/consumables/major-arcane-shard/'),
(31, 'MAJOR ATTUNE POTION', 'Consumable', 'You gain a +1 bonus to your Instinct until your next rest.', 'https://daggerheartsrd.com/consumables/major-attune-potion/'),
(32, 'MAJOR BOLSTER POTION', 'Consumable', 'You gain a +1 bonus to your Strength until your next rest.', 'https://daggerheartsrd.com/consumables/major-bolster-potion/'),
(33, 'MAJOR CHARM POTION', 'Consumable', 'You gain a +1 bonus to your Presence until your next rest.', 'https://daggerheartsrd.com/consumables/major-charm-potion/'),
(34, 'MAJOR CONTROL POTION', 'Consumable', 'You gain a +1 bonus to your Finesse until your next rest.', 'https://daggerheartsrd.com/consumables/major-control-potion/'),
(35, 'MAJOR ENLIGHTEN POTION', 'Consumable', 'You gain a +1 bonus to your Knowledge until your next rest.', 'https://daggerheartsrd.com/consumables/major-enlighten-potion/'),
(36, 'MAJOR HEALTH POTION', 'Consumable', 'Clear 1d4+2 HP.', 'https://daggerheartsrd.com/consumables/major-health-potion/'),
(37, 'MAJOR STAMINA POTION', 'Consumable', 'Clear 1d4+2 Stress.', 'https://daggerheartsrd.com/consumables/major-stamina-potion/'),
(38, 'MAJOR STRIDE POTION', 'Consumable', 'You gain a +1 bonus to your Agility until your next rest.', 'https://daggerheartsrd.com/consumables/major-stride-potion/'),
(39, 'MINOR HEALTH POTION', 'Consumable', 'Clear 1d4 HP.', 'https://daggerheartsrd.com/consumables/minor-health-potion/'),
(40, 'MINOR STAMINA POTION', 'Consumable', 'Clear 1d4 Stress.', 'https://daggerheartsrd.com/consumables/minor-stamina-potion/'),
(41, 'MIRROR OF MARIGOLD', 'Consumable', 'When you take damage, you can spend a Hope to negate that damage, after which the mirror shatters.', 'https://daggerheartsrd.com/consumables/mirror-of-marigold/'),
(42, 'MORPHING CLAY', 'Consumable', 'You can spend 4 Hope to use this clay, altering your face enough to make you unrecognizable until your next rest.', 'https://daggerheartsrd.com/consumables/morphing-clay/'),
(43, 'MYTHIC DUST', 'Consumable', 'You can apply this dust to a weapon that deals magic damage to add a d12 to your next damage roll with that weapon.', 'https://daggerheartsrd.com/consumables/mythic-dust/'),
(44, 'OGRE MUSK', 'Consumable', 'You can use this musk to prevent anyone from tracking you by mundane or magical means until your next rest.', 'https://daggerheartsrd.com/consumables/ogre-musk/'),
(45, 'POTION OF STABILITY', 'Consumable', 'You can drink this potion to choose one additional downtime move.', 'https://daggerheartsrd.com/consumables/potion-of-stability/'),
(46, 'REDTHORN SALIVA', 'Consumable', 'You can apply this saliva to a weapon that deals physical damage to add a d12 to your next damage roll with that weapon.', 'https://daggerheartsrd.com/consumables/redthorn-saliva/'),
(47, 'REPLICATION PARCHMENT', 'Consumable', 'By touching this piece of parchment to another, you can perfectly copy the second parchment''s contents. Once used, this parchment becomes mundane paper.', 'https://daggerheartsrd.com/consumables/replication-parchment/'),
(48, 'SHRINKING POTION', 'Consumable', 'You can drink this potion to halve your size until you choose to drop this form or your next rest. While in this form, you have a +2 bonus to Agility and a -1 penalty to your Proficiency.', 'https://daggerheartsrd.com/consumables/shrinking-potion/'),
(49, 'SLEEPING SAP', 'Consumable', 'You can drink this potion to fall asleep for a full night''s rest. You clear all Stress upon waking.', 'https://daggerheartsrd.com/consumables/sleeping-sap/'),
(50, 'SNAP POWDER', 'Consumable', 'Mark a Stress and clear a HP.', 'https://daggerheartsrd.com/consumables/snap-powder/'),
(51, 'STAMINA POTION', 'Consumable', 'Clear 1d4+1 Stress.', 'https://daggerheartsrd.com/consumables/stamina-potion/'),
(52, 'STARDROP', 'Consumable', 'You can use this stardrop to summon a hailstorm of comets that deals 8d20 physical damage to all targets within Very Far range.', 'https://daggerheartsrd.com/consumables/stardrop/'),
(53, 'STRIDE POTION', 'Consumable', 'You gain a +1 bonus to your next Agility Roll.', 'https://daggerheartsrd.com/consumables/stride-potion/'),
(54, 'SUN TREE SAP', 'Consumable', 'Consume this sap to roll a d6. On a result of 5-6, clear 2 HP. On a result of 2-4, clear 3 Stress. On a result of 1, see through the veil of death and return unscathed, gaining one scar.', 'https://daggerheartsrd.com/consumables/sun-tree-sap/'),
(55, 'SWEET MOSS', 'Consumable', 'You can consume this moss during a rest to clear 1d10 HP or 1d10 Stress.', 'https://daggerheartsrd.com/consumables/sweet-moss/'),
(56, 'UNSTABLE ARCANE SHARD', 'Consumable', 'You can make a Finesse Roll to throw this shard at a group of adversaries within Far range. Targets you succeed against take 1d20 magic damage.', 'https://daggerheartsrd.com/consumables/unstable-arcane-shard/'),
(57, 'VARIK LEAVES', 'Consumable', 'You can eat these paired leaves to immediately gain 2 Hope.', 'https://daggerheartsrd.com/consumables/varik-leaves/'),
(58, 'VIAL OF DARKSMOKE', 'Consumable', 'When an adversary attacks you, use this vial and roll a number of d6 equal to your Agility. Add the highest result to your Evasion against the attack.', 'https://daggerheartsrd.com/consumables/vial-of-darksmoke/'),
(59, 'VIAL OF MOONDRIP', 'Consumable', 'When you drink the contents of this vial, you can see in total darkness until your next rest.', 'https://daggerheartsrd.com/consumables/vial-of-moondrip/'),
(60, 'WINGSPROUT', 'Consumable', 'You gain magic wings that allow you to fly for a number of minutes equal to your level.', 'https://daggerheartsrd.com/consumables/wingsprout/');
