-- Generated from daggerheart.db for Items.

DROP TABLE IF EXISTS Items;

CREATE TABLE Items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_name TEXT NOT NULL UNIQUE,
    subcategory TEXT,
    description_text TEXT NOT NULL,
    source_url TEXT
);

INSERT INTO Items (id, item_name, subcategory, description_text, source_url) VALUES
(1, 'AIRBLADE CHARM', 'Item', 'You can attach this charm to a weapon with a Melee range. Three times per rest, you can activate the charm and attack a target within Close range.', 'https://daggerheartsrd.com/items/airblade-charm/'),
(2, 'ALISTAIR''S TORCH', 'Item', 'You can light this magic torch at will. The flame''s light fills a much larger space than it should, enough to illuminate a cave bright as day.', 'https://daggerheartsrd.com/items/alistairs-torch/'),
(3, 'ARCANE CLOAK', 'Item', 'A creature with a Spellcast trait wearing this cloak can adjust its color, texture, and size at will.', 'https://daggerheartsrd.com/items/arcane-cloak/'),
(4, 'ARCANE PRISM', 'Item', 'Position this prism in a location of your choosing and activate it. All allies within Close range of it gain a +1 bonus to their Spellcast Rolls. While activated, the prism can''t be moved. Once the prism is deactivated, it can''t be activated again until your next long rest.', 'https://daggerheartsrd.com/items/arcane-prism/'),
(5, 'ATTUNE RELIC', 'Item', 'You gain a +1 bonus to your Instinct. You can only carry one relic.', 'https://daggerheartsrd.com/items/attune-relic/'),
(6, 'BAG OF FICKLESAND', 'Item', 'You can convince this small bag of sand to be much heavier or lighter with a successful Presence Roll (10). Additionally, on a successful Finesse Roll (10), you can blow a bit of sand into a target''s face to make them temporarily Vulnerable.', 'https://daggerheartsrd.com/items/bag-of-ficklesand/'),
(7, 'BELT OF UNITY', 'Item', 'Once per session, you can spend 5 Hope to lead a Tag Team Roll with three PCs instead of two.', 'https://daggerheartsrd.com/items/belt-of-unity/'),
(8, 'BLOODSTONE', 'Item', 'You can attach this stone to a weapon that doesn''t already have a feature. The weapon gains the following feature. Brutal: When you roll the maximum value on a damage die, roll an additional damage die.', 'https://daggerheartsrd.com/items/bloodstone/'),
(9, 'BOLSTER RELIC', 'Item', 'You gain a +1 bonus to your Strength. You can only carry one relic.', 'https://daggerheartsrd.com/items/bolster-relic/'),
(10, 'BOX OF MANY GOODS', 'Item', 'Once per long rest, you can open this small box and roll a d12. On a result of 1-6, it''s empty. On a result of 7-10, it contains one random common consumable. On a result of 11-12, it contains two random common consumables.', 'https://daggerheartsrd.com/items/box-of-many-goods/'),
(11, 'CALMING PENDANT', 'Item', 'When you would mark your last Stress, roll a d6. On a result of 5 or higher, don''t mark it.', 'https://daggerheartsrd.com/items/calming-pendant/'),
(12, 'CHARGING QUIVER', 'Item', 'When you succeed on an attack with an arrow stored in this quiver, gain a bonus to the damage roll equal to your current tier.', 'https://daggerheartsrd.com/items/charging-quiver/'),
(13, 'CHARM RELIC', 'Item', 'You gain a +1 bonus to your Presence. You can only carry one relic.', 'https://daggerheartsrd.com/items/charm-relic/'),
(14, 'CLAY COMPANION', 'Item', 'When you sculpt this ball of clay into a clay animal companion, it behaves as that animal. For example, a clay spider can spin clay webs, while a clay bird can fly. The clay companion retains memory and identity across different shapes, but they can adopt new mannerisms with each form.', 'https://daggerheartsrd.com/items/clay-companion/'),
(15, 'COMPANION CASE', 'Item', 'This case can fit a small animal companion. While the companion is inside, the animal and case are immune to all damage and harmful effects.', 'https://daggerheartsrd.com/items/companion-case/'),
(16, 'CONTROL RELIC', 'Item', 'You gain a +1 bonus to your Finesse. You can only carry one relic.', 'https://daggerheartsrd.com/items/control-relic/'),
(17, 'CORRECTOR SPRITE', 'Item', 'This tiny sprite sits in the curve of your ear canal and whispers helpful advice during combat. Once per short rest, you can gain advantage on an attack roll.', 'https://daggerheartsrd.com/items/corrector-sprite/'),
(18, 'DUAL FLASK', 'Item', 'This flask can hold two different liquids. You can swap between them by flipping a small switch on the flask''s side.', 'https://daggerheartsrd.com/items/dual-flask/'),
(19, 'ELUSIVE AMULET', 'Item', 'Once per long rest, you can activate this amulet to become Hidden until you move. While Hidden in this way, you remain unseen even if an adversary moves to where they would normally see you.', 'https://daggerheartsrd.com/items/elusive-amulet/'),
(20, 'EMPTY CHEST', 'Item', 'This magical chest appears empty. When you speak a specific trigger word or action and open the chest, you can see the items stored within it.', 'https://daggerheartsrd.com/items/empty-chest/'),
(21, 'ENLIGHTEN RELIC', 'Item', 'You gain a +1 bonus to your Knowledge. You can only carry one relic.', 'https://daggerheartsrd.com/items/enlighten-relic/'),
(22, 'FIRE JAR', 'Item', 'You can pour out the strange liquid contents of this jar to instantly produce fire. The contents regenerate when you take a long rest.', 'https://daggerheartsrd.com/items/fire-jar/'),
(23, 'FLICKERFLY PENDANT', 'Item', 'While you carry this pendant, your weapons with a Melee range that deal physical damage have a gossamer sheen and can attack targets within Very Close range.', 'https://daggerheartsrd.com/items/flickerfly-pendant/'),
(24, 'GECKO GLOVES', 'Item', 'You can climb up vertical surfaces and across ceilings.', 'https://daggerheartsrd.com/items/gecko-gloves/'),
(25, 'GEM OF ALACRITY', 'Item', 'You can attach this gem to a weapon, allowing you to use your Agility when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-alacrity/'),
(26, 'GEM OF AUDACITY', 'Item', 'You can attach this gem to a weapon, allowing you to use your Presence when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-audacity/'),
(27, 'GEM OF INSIGHT', 'Item', 'You can attach this gem to a weapon, allowing you to use your Instinct when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-insight/'),
(28, 'GEM OF MIGHT', 'Item', 'You can attach this gem to a weapon, allowing you to use your Strength when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-might/'),
(29, 'GEM OF PRECISION', 'Item', 'You can attach this gem to a weapon, allowing you to use your Finesse when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-precision/'),
(30, 'GEM OF SAGACITY', 'Item', 'You can attach this gem to a weapon, allowing you to use your Knowledge when making an attack with that weapon.', 'https://daggerheartsrd.com/items/gem-of-sagacity/'),
(31, 'GLAMOUR STONE', 'Item', 'Activate this pebble-sized stone to memorize the appearance of someone you can see. Spend a Hope to magically recreate this guise on yourself as an illusion.', 'https://daggerheartsrd.com/items/glamour-stone/'),
(32, 'GLIDER', 'Item', 'While falling, you can mark a Stress to deploy this small parachute and glide safely to the ground.', 'https://daggerheartsrd.com/items/glider/'),
(33, 'GREATSTONE', 'Item', 'You can attach this stone to a weapon that doesn''t already have a feature. The weapon gains the following feature. Powerful: On a successful attack, roll an additional damage die and discard the lowest result.', 'https://daggerheartsrd.com/items/greatstone/'),
(34, 'HOMING COMPASSES', 'Item', 'These two compasses point toward each other no matter how far apart they are.', 'https://daggerheartsrd.com/items/homing-compasses/'),
(35, 'HONING RELIC', 'Item', 'You gain a +1 bonus to an Experience of your choice. You can only carry one relic.', 'https://daggerheartsrd.com/items/honing-relic/'),
(36, 'HOPEKEEPER LOCKET', 'Item', 'During a long rest, if you have 6 Hope, you can spend a Hope to imbue this locket with your bountiful resolve. When you have 0 Hope, you can use the locket to immediately gain a Hope. The locket must be re-imbued before it can be used this way again.', 'https://daggerheartsrd.com/items/hopekeeper-locket/'),
(37, 'INFINITE BAG', 'Item', 'When you store items in this bag, they are kept in a pocket dimension that never runs out of space. You can retrieve an item at any time.', 'https://daggerheartsrd.com/items/infinite-bag/'),
(38, 'LASKETIDER BOOTS', 'Item', 'You can walk on the surface of water as if it were soft ground.', 'https://daggerheartsrd.com/items/lasketider-boots/'),
(39, 'LOREKEEPER', 'Item', 'You can store the name and details of up to three hostile creatures inside this book. You gain a +1 bonus to action rolls against those creatures.', 'https://daggerheartsrd.com/items/lorekeeper/'),
(40, 'MANACLES', 'Item', 'This pair of locking cuffs comes with a key.', 'https://daggerheartsrd.com/items/manacles/'),
(41, 'MINOR HEALTH POTION RECIPE', 'Item', 'As a downtime move, you can use a vial of blood to craft a Minor Health Potion.', 'https://daggerheartsrd.com/items/minor-health-potion-recipe/'),
(42, 'MINOR STAMINA POTION RECIPE', 'Item', 'As a downtime move, you can use the bone of a creature to craft a Minor Stamina Potion.', 'https://daggerheartsrd.com/items/minor-stamina-potion-recipe/'),
(43, 'MYTHIC DUST RECIPE', 'Item', 'As a downtime move, you can use a handful of fine gold dust to craft Mythic Dust.', 'https://daggerheartsrd.com/items/mythic-dust-recipe/'),
(44, 'PARAGON''S CHAIN', 'Item', 'As a downtime move, you can meditate on an ideal or principle you hold dear and focus your will into this chain. Once per long rest, you can spend a Hope to roll a d20 as your Hope Die for rolls that directly align with that principle.', 'https://daggerheartsrd.com/items/paragons-chain/'),
(45, 'PHOENIX FEATHER', 'Item', 'If you have at least one Phoenix Feather on you when you fall unconscious, you gain a +1 bonus to the roll you make to determine whether you gain a scar.', 'https://daggerheartsrd.com/items/phoenix-feather/'),
(46, 'PIERCING ARROWS', 'Item', 'Three times per rest when you succeed on an attack with one of these arrows, you can add your Proficiency to the damage roll.', 'https://daggerheartsrd.com/items/piercing-arrows/'),
(47, 'PIPER WHISTLE', 'Item', 'This handcrafted whistle has a distinctive sound. When you blow this whistle, its piercing tone can be heard within a 1-mile radius.', 'https://daggerheartsrd.com/items/piper-whistle/'),
(48, 'PORTAL SEED', 'Item', 'You can plant this seed in the ground to grow a portal in that spot. The portal is ready to use in 24 hours. You can use this portal to travel to any other location where you planted a portal seed. A portal can be destroyed by dealing any amount of magic damage to it.', 'https://daggerheartsrd.com/items/portal-seed/'),
(49, 'PREMIUM BEDROLL', 'Item', 'During downtime, you automatically clear a Stress.', 'https://daggerheartsrd.com/items/premium-bedroll/'),
(50, 'RING OF RESISTANCE', 'Item', 'Once per long rest, you can activate this ring after a successful attack against you to halve the damage.', 'https://daggerheartsrd.com/items/ring-of-resistance/'),
(51, 'RING OF SILENCE', 'Item', 'Spend a Hope to activate this ring. Your footsteps are silent until your next rest.', 'https://daggerheartsrd.com/items/ring-of-silence/'),
(52, 'RING OF UNBREAKABLE RESOLVE', 'Item', 'Once per session, when the GM spends a Fear, you can spend 4 Hope to cancel the effects of that spent Fear.', 'https://daggerheartsrd.com/items/ring-of-unbreakable-resolve/'),
(53, 'SHARD OF MEMORY', 'Item', 'Once per long rest, you can spend 2 Hope to recall a domain card from your vault instead of paying its Recall Cost.', 'https://daggerheartsrd.com/items/shard-of-memory/'),
(54, 'SKELETON KEY', 'Item', 'When you use this key to open a locked door, you gain advantage on the Finesse Roll.', 'https://daggerheartsrd.com/items/skeleton-key/'),
(55, 'SPEAKING ORBS', 'Item', 'This pair of orbs allows any creatures holding them to communicate with each other across any distance.', 'https://daggerheartsrd.com/items/speaking-orbs/'),
(56, 'STRIDE RELIC', 'Item', 'You gain a +1 bonus to your Agility. You can only carry one relic.', 'https://daggerheartsrd.com/items/stride-relic/'),
(57, 'SUSPENDED ROD', 'Item', 'This flat rod is inscribed with runes. When you activate the rod, it is immediately suspended in place. Until the rod is deactivated, it can''t move, doesn''t abide by the rules of gravity, and remains in place.', 'https://daggerheartsrd.com/items/suspended-rod/'),
(58, 'VALORSTONE', 'Item', 'You can attach this stone to armor that doesn''t already have a feature. The armor gains the following feature. Resilient: Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot.', 'https://daggerheartsrd.com/items/valorstone/'),
(59, 'VIAL OF DARKSMOKE RECIPE', 'Item', 'As a downtime move, you can mark a Stress to craft a Vial of Darksmoke.', 'https://daggerheartsrd.com/items/vial-of-darksmoke-recipe/'),
(60, 'WOVEN NET', 'Item', 'You can make a Finesse Roll using this net to trap a small creature. A trapped target can break free with a successful Attack Roll (16).', 'https://daggerheartsrd.com/items/woven-net/');
